import requests
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO # To treat bytes as a file

# 1. Get the Metadata (JSON) [data about data] 
# NASA requires a key; 'DEMO_KEY' is the public one for testing.
metadata_req = requests.get('https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY')
data = metadata_req.json() #from the metadata,
image_url = data.get('url') #get The actual link to the image

# 2. Get the Actual Image with the image link
image_req = requests.get(image_url)

# BytesIO(image_req.content) makes the raw data "look" like a file to Pillow
img = Image.open(BytesIO(image_req.content))

# 3. Setup Drawing
draw = ImageDraw.Draw(img)
# Fallback: If EXIF is empty, use the NASA Title
watermark_text = data.get('title', "Shadow Army Intel")

# Note: "arial.ttf" might not be found on all systems (especially Linux/Mac). 
# If it fails, use ImageFont.load_default()
try:
    font = ImageFont.truetype("arial.ttf", 40)
except:
    font = ImageFont.load_default()

# 4. Calculation for Positioning
# We use textbbox to find the "Box" the text takes up
bbox = draw.textbbox((0, 0), watermark_text, font=font)
text_width = bbox[2] - bbox[0]
text_height = bbox[3] - bbox[1]

image_width, image_height = img.size
position = (image_width - text_width - 20, image_height - text_height - 20)

# 5. Execute & Save
draw.text(position, watermark_text, font=font, fill=(255, 255, 255))
img.save("nasa_scout_report.jpg")
img.show()

from fpdf import FPDF


# 1. Initialize the PDF
pdf = FPDF()
pdf.add_page()

# 2. The Title
pdf.set_font("Arial", 'B', 16) # 'B' for Bold
pdf.cell(0, 10, txt=data.get('title', 'NASA Intel Report'), ln=True, align='C')
pdf.ln(10) # Add a line break (space)

# 3. The Image
# We place the image. 10 is the X, 30 is the Y. 
# We set the width to 180 to fit the page.
pdf.image("nasa_scout_report.jpg", x=15, y=30, w=180)
pdf.ln(130) # Space below the image (adjust based on image height)

# 4. The Explanation (The Body Text)
pdf.set_font("Arial", size=12)
explanation = data.get('explanation', 'No description available.')
# multi_cell automatically wraps the text so it doesn't go off the page
pdf.multi_cell(0, 10, txt=explanation)

# 5. Footer (The Monarch's Mark)
pdf.set_y(-25) # Move to 25mm from the bottom
pdf.set_font("Arial", 'I', 8) # 'I' for Italic
pdf.cell(0, 10, txt="Generated by Arachnet Intelligence - Shadow Army 2026", align='C')

# 6. Final Output
pdf.output("NASA_Daily_Brief.pdf")
print("Report generated: NASA_Daily_Brief.pdf")







